"""
symbolic_frontier_induction.py
==============================
Symbolic next-step report for the moving quotient frontier.

This is deliberately not a brute-force search.  It records the recurrence that
the quotient report exposed, rewrites the danger/return tests as exact integer
conditions, and isolates the missing induction invariant.
"""

import json
import math
from pathlib import Path

ALPHA = math.log2(3)
BASE = (306, 485)
LOWER_STEP = (665, 1054)  # lower convergent after 306/485: 1054/665 < log2(3)
B_LIMIT = 200_001


def exact_side(o, c):
    left = 1 << c
    right = 3 ** o
    if left > right:
        return "positive", left - right
    if left < right:
        return "debt", right - left
    return "equal", 0


def upper_wall_sequence(count):
    """Upper semiconvergents after 306/485 generated by adding 665/1054."""
    out = []
    for t in range(count):
        o = BASE[0] + (t + 1) * LOWER_STEP[0]
        c = BASE[1] + (t + 1) * LOWER_STEP[1]
        side, gap = exact_side(o, c)
        out.append({
            "t": t + 1,
            "pair": (o, c),
            "delta": c - o * ALPHA,
            "side": side,
            "gap_bits": gap.bit_length(),
        })
    return out


def lower_wall_before_upper(seq):
    out = []
    for item in seq:
        o, c = item["pair"]
        side, gap = exact_side(o, c - 1)
        out.append({
            "upper_pair": (o, c),
            "lower_neighbor": (o, c - 1),
            "delta": c - 1 - o * ALPHA,
            "side": side,
            "gap_bits": gap.bit_length(),
        })
    return out


def load_frontier_sample():
    path = Path("excursion_quotient_report.json")
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("open_frontier", [])


def verify_sample_recurrence(frontier):
    checks = []
    for item in frontier:
        key = item.get("key")
        if not key or len(key) != 4:
            continue
        s, q, u, v = key
        if s != 0:
            continue
        expected = sorted([(u, v + 1, "0"), (u + 1, v + 1, "10")])
        observed = sorted(
            (x["key"][2], x["key"][3], x["path"])
            for x in item.get("boundary_successors", [])
            if x.get("kind") == "boundary"
        )
        checks.append({
            "key": key,
            "pair": item.get("pair"),
            "ok": observed == expected,
            "observed": observed,
            "expected": expected,
        })
    return checks


def build_report():
    upper = upper_wall_sequence(8)
    frontier = load_frontier_sample()
    checks = verify_sample_recurrence(frontier)
    recurrence_verified = bool(checks) and all(x["ok"] for x in checks)

    report = {
        "recurrence_guess": {
            "state": "reachable boundary frontier F(o,c) with s=level-c=0 and q=0",
            "zero_branch": "F(o,c) -> F(o,c+1), parity suffix 0",
            "one_branch": "F(o,c) -> F(o+1,c+1), parity suffix 10",
            "word_formula": (
                "After t frontier cycles and h one-branches, "
                "F(o,c) reaches F(o+h,c+t)."
            ),
        },
        "equations": {
            "delta": "Delta(o,c) = c - o*log2(3)",
            "zero_delta": "Delta(o,c+1) = Delta(o,c) + 1",
            "one_delta": "Delta(o+1,c+1) = Delta(o,c) + 1 - log2(3)",
            "word_delta": "Delta(o+h,c+t) = Delta(o,c) + t - h*log2(3)",
            "exact_debt_test": "2^c <= 3^o",
            "exact_positive_test": "2^c > 3^o",
            "exact_B_test": "B = ceil(b / (2^c - 3^o)) <= 200001",
        },
        "continued_fraction_structure": {
            "base_upper_wall": BASE,
            "next_lower_convergent_step": LOWER_STEP,
            "upper_wall_sequence": upper,
            "lower_neighbors": lower_wall_before_upper(upper),
            "explanation": (
                "The frontier recurrence generates integer lattice pairs "
                "(o+h,c+t). The hardest positive returns are the upper best "
                "approximants to log2(3), because they minimize 2^c-3^o. "
                "The adjacent lower neighbors have 2^c<3^o, so no B exists."
            ),
        },
        "proven_now": {
            "sampled_reachable_frontier_recurrence": recurrence_verified,
            "frontier_checks": checks[:50],
            "quotient_conflicts": 0,
            "key_alone_sufficient": False,
        },
        "not_proven": {
            "global_reachable_frontier_invariant": (
                "Need to prove every open frontier state has q=0 and follows "
                "the boundary recurrence, not only the exported samples."
            ),
            "forced_return": (
                "The recurrence alone permits an all-one path with Delta "
                "decreasing by log2(3)-1 each cycle. A second invariant must "
                "bound or forbid long one-heavy frontier words."
            ),
            "B_control": (
                "Positive margin is not enough. The return must also satisfy "
                "ceil(b/(2^c-3^o)) <= 200001."
            ),
        },
        "next_file_to_build": "frontier_word_invariant.py",
        "next_file_goal": (
            "Track the frontier word/count invariant that limits h in "
            "Delta(o+h,c+t)=Delta(o,c)+t-h*log2(3), and connect each allowed "
            "debt interval to a certified positive return with exact B."
        ),
    }
    return report


def main():
    report = build_report()
    with open("symbolic_frontier_induction_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print("=" * 78)
    print("SYMBOLIC FRONTIER INDUCTION REPORT")
    print("=" * 78)
    print("Recurrence guess:")
    for k, v in report["recurrence_guess"].items():
        print(f"  {k}: {v}")
    print()
    print("Upper continued-fraction wall sequence after (306,485):")
    for item in report["continued_fraction_structure"]["upper_wall_sequence"][:6]:
        print(f"  {tuple(item['pair'])} delta={item['delta']:.12f} side={item['side']}")
    print()
    print("What is proven:")
    print(f"  sampled reachable frontier recurrence: {report['proven_now']['sampled_reachable_frontier_recurrence']}")
    print("  exact debt/positive tests are integer tests: 2^c <=/> 3^o")
    print()
    print("What remains open:")
    for v in report["not_proven"].values():
        print(f"  - {v}")
    print()
    print(f"Next file to build: {report['next_file_to_build']}")
    print("Report: symbolic_frontier_induction_report.json")


if __name__ == "__main__":
    main()
